name: flutter_shape_editor
description: An online editor for editing various Flutter shapes and morph between them.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  morphable_shape:
    path: ../

  length_unit: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon-512.png
    - assets/images/Icon-192.png

