name: morphable_shape
description: A Flutter package for creating various shapes that are responsive and can morph betweem each other.
version: 1.4.4
repository: https://github.com/KevinVan720/morphable_shape

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_class_parser: ^0.1.9
  dimension: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

